// regression baseline: the 453 named math symbols that render correctly
// today, out of 459 in katex's math table. The failures are covered
// separately in math_glyph_gaps.jsx. A font-table regression breaks a row here.
<VStack spacing={0.02}>
  <Latex>{"\\equiv \\; \\prec \\; \\succ \\; \\sim \\; \\perp \\; \\preceq \\; \\succeq \\; \\simeq \\; \\mid \\; \\ll \\; \\gg \\; \\asymp \\; \\parallel \\; \\bowtie \\; \\smile \\; \\sqsubseteq \\; \\sqsupseteq \\; \\doteq \\; \\frown \\; \\ni \\; \\propto \\; \\vdash \\; \\dashv \\; \\owns \\; \\ldotp \\; \\cdotp"}</Latex>
  <Latex>{"\\# \\; \\& \\; \\aleph \\; \\forall \\; \\hbar \\; \\exists \\; \\nabla \\; \\flat \\; \\ell \\; \\natural \\; \\clubsuit \\; \\wp \\; \\sharp \\; \\diamondsuit \\; \\Re \\; \\heartsuit \\; \\Im \\; \\spadesuit \\; \\S \\; \\P \\; \\dag \\; \\ddag \\; \\rmoustache \\; \\lmoustache \\; \\rgroup \\; \\lgroup"}</Latex>
  <Latex>{"\\mp \\; \\ominus \\; \\uplus \\; \\sqcap \\; \\ast \\; \\sqcup \\; \\bigcirc \\; \\bullet \\; \\ddagger \\; \\wr \\; \\amalg \\; \\And \\; \\longleftarrow \\; \\Leftarrow \\; \\Longleftarrow \\; \\longrightarrow \\; \\Rightarrow \\; \\Longrightarrow \\; \\leftrightarrow \\; \\longleftrightarrow \\; \\Leftrightarrow \\; \\Longleftrightarrow \\; \\mapsto \\; \\longmapsto \\; \\nearrow \\; \\hookleftarrow"}</Latex>
  <Latex>{"\\hookrightarrow \\; \\searrow \\; \\leftharpoonup \\; \\rightharpoonup \\; \\swarrow \\; \\leftharpoondown \\; \\rightharpoondown \\; \\nwarrow \\; \\rightleftharpoons \\; \\nless \\; \\@nleqslant \\; \\@nleqq \\; \\lneq \\; \\lneqq \\; \\@lvertneqq \\; \\lnsim \\; \\lnapprox \\; \\nprec \\; \\npreceq \\; \\precnsim \\; \\precnapprox \\; \\nsim \\; \\@nshortmid \\; \\nmid \\; \\nvdash \\; \\nvDash"}</Latex>
  <Latex>{"\\ntriangleleft \\; \\ntrianglelefteq \\; \\subsetneq \\; \\@varsubsetneq \\; \\subsetneqq \\; \\@varsubsetneqq \\; \\ngtr \\; \\@ngeqslant \\; \\@ngeqq \\; \\gneq \\; \\gneqq \\; \\@gvertneqq \\; \\gnsim \\; \\gnapprox \\; \\nsucc \\; \\nsucceq \\; \\succnsim \\; \\succnapprox \\; \\ncong \\; \\@nshortparallel \\; \\nparallel \\; \\nVDash \\; \\ntriangleright \\; \\ntrianglerighteq \\; \\@nsupseteqq \\; \\supsetneq"}</Latex>
  <Latex>{"\\@varsupsetneq \\; \\supsetneqq \\; \\@varsupsetneqq \\; \\nVdash \\; \\precneqq \\; \\succneqq \\; \\@nsubseteqq \\; \\unlhd \\; \\unrhd \\; \\nleftarrow \\; \\nrightarrow \\; \\nLeftarrow \\; \\nRightarrow \\; \\nleftrightarrow \\; \\nLeftrightarrow \\; \\vartriangle \\; \\hslash \\; \\triangledown \\; \\lozenge \\; \\circledS \\; \\circledR \\; \\measuredangle \\; \\nexists \\; \\mho \\; \\Finv \\; \\Game"}</Latex>
  <Latex>{"\\backprime \\; \\blacktriangle \\; \\blacktriangledown \\; \\blacksquare \\; \\blacklozenge \\; \\bigstar \\; \\sphericalangle \\; \\complement \\; \\eth \\; \\diagup \\; \\diagdown \\; \\square \\; \\Box \\; \\Diamond \\; \\yen \\; \\checkmark \\; \\beth \\; \\daleth \\; \\gimel \\; \\digamma \\; \\varkappa \\; \\@ulcorner \\; \\@urcorner \\; \\@llcorner \\; \\@lrcorner \\; \\leqq"}</Latex>
  <Latex>{"\\leqslant \\; \\eqslantless \\; \\lesssim \\; \\lessapprox \\; \\approxeq \\; \\lessdot \\; \\lll \\; \\lessgtr \\; \\lesseqgtr \\; \\lesseqqgtr \\; \\doteqdot \\; \\risingdotseq \\; \\fallingdotseq \\; \\backsim \\; \\backsimeq \\; \\subseteqq \\; \\Subset \\; \\sqsubset \\; \\preccurlyeq \\; \\curlyeqprec \\; \\precsim \\; \\precapprox \\; \\vartriangleleft \\; \\trianglelefteq \\; \\vDash \\; \\Vvdash"}</Latex>
  <Latex>{"\\smallsmile \\; \\smallfrown \\; \\bumpeq \\; \\Bumpeq \\; \\geqq \\; \\geqslant \\; \\eqslantgtr \\; \\gtrsim \\; \\gtrapprox \\; \\gtrdot \\; \\ggg \\; \\gtrless \\; \\gtreqless \\; \\gtreqqless \\; \\eqcirc \\; \\circeq \\; \\triangleq \\; \\thicksim \\; \\thickapprox \\; \\supseteqq \\; \\Supset \\; \\sqsupset \\; \\succcurlyeq \\; \\curlyeqsucc \\; \\succsim \\; \\succapprox"}</Latex>
  <Latex>{"\\vartriangleright \\; \\trianglerighteq \\; \\Vdash \\; \\shortmid \\; \\shortparallel \\; \\between \\; \\pitchfork \\; \\varpropto \\; \\blacktriangleleft \\; \\therefore \\; \\backepsilon \\; \\blacktriangleright \\; \\because \\; \\llless \\; \\gggtr \\; \\lhd \\; \\rhd \\; \\eqsim \\; \\Join \\; \\Doteq \\; \\dotplus \\; \\smallsetminus \\; \\Cap \\; \\Cup \\; \\doublebarwedge \\; \\boxminus"}</Latex>
  <Latex>{"\\boxplus \\; \\divideontimes \\; \\ltimes \\; \\rtimes \\; \\leftthreetimes \\; \\rightthreetimes \\; \\curlywedge \\; \\curlyvee \\; \\circleddash \\; \\circledast \\; \\centerdot \\; \\intercal \\; \\doublecap \\; \\doublecup \\; \\boxtimes \\; \\dashrightarrow \\; \\dashleftarrow \\; \\leftleftarrows \\; \\leftrightarrows \\; \\Lleftarrow \\; \\twoheadleftarrow \\; \\leftarrowtail \\; \\looparrowleft \\; \\leftrightharpoons \\; \\curvearrowleft \\; \\circlearrowleft"}</Latex>
  <Latex>{"\\Lsh \\; \\upuparrows \\; \\upharpoonleft \\; \\downharpoonleft \\; \\multimap \\; \\leftrightsquigarrow \\; \\rightrightarrows \\; \\rightleftarrows \\; \\twoheadrightarrow \\; \\rightarrowtail \\; \\looparrowright \\; \\curvearrowright \\; \\circlearrowright \\; \\Rsh \\; \\downdownarrows \\; \\upharpoonright \\; \\downharpoonright \\; \\rightsquigarrow \\; \\leadsto \\; \\Rrightarrow \\; \\restriction \\; \\$ \\; \\% \\; \\_ \\; \\angle \\; \\infty"}</Latex>
  <Latex>{"\\prime \\; \\triangle \\; \\Gamma \\; \\Delta \\; \\Theta \\; \\Lambda \\; \\Xi \\; \\Pi \\; \\Sigma \\; \\Upsilon \\; \\Phi \\; \\Psi \\; \\Omega \\; \\neg \\; \\lnot \\; \\top \\; \\bot \\; \\emptyset \\; \\varnothing \\; \\alpha \\; \\beta \\; \\gamma \\; \\delta \\; \\epsilon \\; \\zeta \\; \\eta"}</Latex>
  <Latex>{"\\theta \\; \\iota \\; \\kappa \\; \\lambda \\; \\mu \\; \\nu \\; \\xi \\; \\omicron \\; \\pi \\; \\rho \\; \\sigma \\; \\tau \\; \\upsilon \\; \\phi \\; \\chi \\; \\psi \\; \\omega \\; \\varepsilon \\; \\vartheta \\; \\varpi \\; \\varrho \\; \\varsigma \\; \\varphi \\; \\cdot \\; \\circ \\; \\div"}</Latex>
  <Latex>{"\\pm \\; \\times \\; \\cap \\; \\cup \\; \\setminus \\; \\land \\; \\lor \\; \\wedge \\; \\vee \\; \\surd \\; \\langle \\; \\lvert \\; \\lVert \\; \\rangle \\; \\rvert \\; \\rVert \\; \\approx \\; \\cong \\; \\ge \\; \\geq \\; \\gets \\; \\gt \\; \\in \\; \\@not \\; \\subset \\; \\supset"}</Latex>
  <Latex>{"\\subseteq \\; \\supseteq \\; \\nsubseteq \\; \\nsupseteq \\; \\models \\; \\leftarrow \\; \\le \\; \\leq \\; \\lt \\; \\rightarrow \\; \\to \\; \\ngeq \\; \\nleq \\; \\  \\; \\nobreakspace \\; \\barwedge \\; \\veebar \\; \\odot \\; \\oplus \\; \\otimes \\; \\partial \\; \\oslash \\; \\circledcirc \\; \\boxdot \\; \\bigtriangleup \\; \\bigtriangledown"}</Latex>
  <Latex>{"\\dagger \\; \\diamond \\; \\star \\; \\triangleleft \\; \\triangleright \\; \\{ \\; \\} \\; \\lbrace \\; \\rbrace \\; \\lbrack \\; \\rbrack \\; \\lparen \\; \\rparen \\; \\lfloor \\; \\rfloor \\; \\lceil \\; \\rceil \\; \\vert \\; \\| \\; \\Vert \\; \\uparrow \\; \\Uparrow \\; \\downarrow \\; \\Downarrow \\; \\updownarrow \\; \\Updownarrow"}</Latex>
  <Latex>{"\\mathellipsis \\; \\ldots \\; \\@cdots \\; \\ddots \\; \\varvdots \\; \\@imath \\; \\@jmath \\; \\degree \\; \\pounds \\; \\mathsterling \\; \\maltese"}</Latex>
</VStack>
